Seems we now may need libkrb5-dev as a dependency
error /root/parts/vscode-json-languageserver/build/node_modules/kerberos: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi || node-gyp rebuild
Arguments:
Directory: /root/parts/vscode-json-languageserver/build/node_modules/kerberos
Output:
prebuild-install warn This package does not support N-API version 25.4.0
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.17.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/root/parts/vscode-json-languageserver/install/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/parts/vscode-json-languageserver/build/node_modules/kerberos/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/parts/vscode-json-languageserver/install/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/25.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/25.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/root/parts/vscode-json-languageserver/install/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/25.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/parts/vscode-json-languageserver/build/node_modules/kerberos',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/root/parts/vscode-json-languageserver/build/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/src/kerberos.o
In file included from ../src/kerberos_common.h:5,
                 from ../src/kerberos.h:12,
                 from ../src/kerberos.cc:1:
../src/unix/kerberos_gss.h:21:14: fatal error: gssapi/gssapi.h: No such file or directory
   21 |     #include <gssapi/gssapi.h>
      |              ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [kerberos.target.mk:128: Release/obj.target/kerberos/src/kerberos.o] Error 1
make: Leaving directory '/root/parts/vscode-json-languageserver/build/node_modules/kerberos/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/parts/vscode-json-languageserver/install/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.0-1042-azure
gyp ERR! command "/root/parts/vscode-json-languageserver/install/bin/node" "/root/parts/vscode-json-languageserver/install/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/parts/vscode-json-languageserver/build/node_modules/kerberos
gyp ERR! node -v v18.17.1
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok

Signed-off-by: Alex Murray <murray.alex@gmail.com>